myproject/core/urls.py
from django.conf.urls import url
from myproject.core import views as v

urlpatterns = [
    url(r'^$', v.home, name='home'),
    url(r'^add/$', v.contact_add, name='contact_add'),
    url(r'^(?P<pk>[^/]+)/json/$', v.contact_json, name='contact_json'),
    url(r'^(?P<pk>[^/]+)/edit/$', v.contact_edit, name='contact_edit'),
    url(r'^(?P<pk>[^/]+)/delete/$', v.contact_delete, name='contact_delete'),
]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('myproject.core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
]

myproject/core/models.py
import uuid
from django.db import models


TREATMENT = (
    ('a', 'Arq.'),
    ('aa', 'Arqa.'),
    ('d', 'Dona'),
    ('dr', 'Dr.'),
    ('dra', 'Dra.'),
    ('e', 'Eng.'),
    ('ea', u'Engª.'),
    ('p', 'Prof.'),
    ('pa', 'Profa.'),
    ('sr', 'Sr.'),
    ('sra', 'Sra.'),
    ('srta', 'Srta.'),
)


class Contact(models.Model):
    # Gera um uuid de 32 caracteres
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    treatment = models.CharField(
        'tratamento', max_length=4, choices=TREATMENT, null=True, blank=True)
    first_name = models.CharField('nome', max_length=50)
    last_name = models.CharField(
        'sobrenome', max_length=50, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField('telefone', max_length=20, null=True, blank=True)

    class Meta:
        # ordering = ('first_name',)
        verbose_name = 'contato'
        verbose_name_plural = 'contatos'

    def __str__(self):
        name = [self.get_treatment_display(), self.first_name, self.last_name]
        return ' '.join(filter(None, name))

myproject/core/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'

myproject/core/views.py
from django.contrib import messages
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from .forms import ContactForm
from .models import Contact


def home(request):
    contacts = Contact.objects.all()
    ctx = {
        'contacts': contacts,
        'contact_form': ContactForm
    }
    return render(request, 'index.html', ctx)


def contact_add(request):
    if request.is_ajax() and request.method == 'POST':
        form = ContactForm(request.POST)
        if not form.is_valid():
            error = {'error': form.errors}
            return JsonResponse(error, status=422)

        treatment = request.POST.get('treatment')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        f = form.save()
        name = [f.get_treatment_display(), f.first_name, f.last_name]
        name = ' '.join(filter(None, name))
        ctx = {
            'id': f.id,
            'name': name,
            'email': f.email,
            'phone': f.phone,
        }
        return JsonResponse(ctx)
    else:
        messages.error(request, 'Favor preencher o nome do contato.')
        return HttpResponseRedirect(reverse('home'))


def contact_json(request, pk):
    contact = Contact.objects.filter(pk=pk)
    data = serializers.serialize('json', contact)
    return HttpResponse(data, content_type='application/json')


def contact_edit(request, pk):
    if request.is_ajax() and request.method == 'POST':
        pk = request.POST.get('contact_edit_id')
        contact = get_object_or_404(Contact, pk=pk)
        # Usando instance não precisa pegar os campos um a um.
        # form = CustomerForm(request.POST, instance=customer)

        # if not form.is_valid():
        #     error = {'error': form.errors}
        #     return JsonResponse(error, status=422)

        contact.treatment = request.POST.get('treatment')
        contact.first_name = request.POST.get('first_name')
        contact.last_name = request.POST.get('last_name')
        contact.email = request.POST.get('email')
        contact.phone = request.POST.get('phone')
        contact.save()
        response = {'status': 'update'}
        return JsonResponse(response)
    else:
        return HttpResponseRedirect(reverse('home'))


def contact_delete(request, pk):
    if request.is_ajax() and request.method == 'POST':
        contact_id = request.POST.get('contact_id')
        print(contact_id)
        contact = Contact.objects.get(pk=contact_id)
        contact.delete()
        ctx = {'status': 'Contato deletado com sucesso.'}
        return JsonResponse(ctx)

myproject/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Frontend Experience</title>
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/starter-template.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      {% include "nav.html" %}
      {% block content %}{% endblock content %}
    </div>
  </div>
</div>

<script src="{% static 'js/faker.js' %}"></script>

{% block js %}{% endblock js %}

</body>
</html>

myproject/core/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap %}

{% block content %}

  <div class="starter-template">
    <h1>Single Page Application</h1>
    <p class="lead">Exemplo de uma SPA com Django, Ajax e jQuery.</p>
  </div>
  <hr>
  <div class="col-sm-4 col-sm-offset-4">
    <button id="add_contact" class="btn btn-primary" data-target="#add_contact_modal" data-toggle="modal">
      <i class="fa fa-plus"></i> Contato
    </button>
    <div id="list_contact" class="list-group">
      {% for contact in contacts %}
        <div id="item_{{ contact.id }}" class="list-group-item">
          <span id="delete_contact" class="js-delete-contact pull-right" data-id="{{ contact.id }}" data-contact="{{ contact }}" data-target="#del_contact_modal" data-toggle="modal"><i class="fa fa-lg fa-times"></i></span>
          <span id="edit_contact" class="js-edit-contact pull-right" data-id="{{ contact.id }}" data-url="{% url 'core:contact_json' pk=contact.pk %}" data-target="#edit_contact_modal" data-toggle="modal"><i class="fa fa-lg fa-pencil-square-o"></i></span>
          <p><b>Nome:</b> {{ contact }}</p>
          <p><b>e-mail:</b> {{ contact.email }}</p>
          <p><b>Telefone:</b> {{ contact.phone }}</p>
        </div>
      {% endfor %}
    </div>
  </div>

<!-- Add Contact Modal -->
<div class="modal fade" id="add_contact_modal" role="dialog" aria-labelledby="addContactModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                 
                <button id="dismiss_contact_close" type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title" id="addContactModalLabel">
                    Novo Contato
                </h4>
            </div>
            <form id="add_contact_form" action="." method="POST">
              <div class="modal-body">
                {% csrf_token %}
                {{ contact_form|bootstrap }}
              </div>
              <div class="modal-footer">
                   
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                  <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </form>
        </div> <!-- modal-content -->
        
    </div> <!-- modal-dialog -->
    
</div> <!-- end modal -->

<!-- Edit Contact Modal -->
<div class="modal fade" id="edit_contact_modal" role="dialog" aria-labelledby="editContactModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                 
                <button id="dismiss_edit_contact_close" type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title" id="editContactModalLabel">
                    Editar Contato
                </h4>
            </div>
            <form id="edit_contact_form" action="." method="POST">
              <div class="modal-body">
                <div id="id_edit_contact"></div>
                {% csrf_token %}
                {{ contact_form|bootstrap }}
              </div>
              <div class="modal-footer">
                   
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                  <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </form>
        </div> <!-- modal-content -->
        
    </div> <!-- modal-dialog -->
    
</div> <!-- end modal -->

<!-- Delete Contact Modal -->
<div class="modal fade" id="del_contact_modal" role="dialog" aria-labelledby="delContactModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                 
                <button id="dismiss_del_contact_close" type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h4 class="modal-title" id="delContactModalLabel">
                    Deletar Contato
                </h4>
            </div>
            <form id="del_contact_form" action="." method="POST">
              <div id="id_del_contact" class="modal-body"></div>
              <div class="modal-footer">
                   
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                  <button type="submit" class="btn btn-danger">Deletar</button>
              </div>
            </form>
        </div> <!-- modal-content -->
        
    </div> <!-- modal-dialog -->
    
</div> <!-- end modal -->

{% endblock content %}

{% block js %}

  <script src="{% static 'js/django-ajax-setup.js' %}"></script>

  <script>
  $('#add_contact_form').on('submit', function(e) {
    e.preventDefault();
    add_contact_post();
  });

  function add_contact_post() {
    $.ajax({
      url: "{% url 'core:contact_add' %}",
      type: "POST",
      data: {
        treatment: $('#id_treatment').val(),
        first_name: $('#id_first_name').val(),
        last_name: $('#id_last_name').val(),
        email: $('#id_email').val(),
        phone: $('#id_phone').val(),
      },
      success: function(response) {
        // remove os valores dos inputs
        $('#add_contact_form')[0].reset();
        $('#dismiss_contact_close').click();
        // Adicionando novo contato na lista
        $('#list_contact').prepend(
          '<div class="list-group-item">' +
          '<span id="delete_contact" class="js-delete-contact pull-right" data-id="' + response.id + '" data-contact="' + response.name + '" data-target="#del_contact_modal" data-toggle="modal"><i class="fa fa-lg fa-times"></i></span>' +
          '<span id="edit_contact" class="pull-right"><i class="fa fa-lg fa-pencil-square-o"></i></span>' +
          '<p><b>Nome:</b> ' + response.name + '</p>' +
          '<p><b>e-mail:</b> ' + response.email + '</p>' +
          '<p><b>Telefone:</b> ' + response.phone + '</p>' +
          '</div>'
        );
      },
      error: function(xhr, errmsg, err) {
        console.log('Ocorreu um erro!');
      },
    });
  }

  // Insere valores nos campos de edit_contact_form
  $('.js-edit-contact').on('click', function() {
    // Remove add_contact_form
    $('#add_contact_form').remove();
    $('#contact_edit_id').remove();
    let id_edit = $(this).data('id');
    $('#id_edit_contact').append('<input id="contact_edit_id" name="contact_edit_id" style="display:none;" value="' + id_edit + '">');
    let url = $(this).data('url');
    $.getJSON(url, function(data) {
        $('#id_treatment').val(data[0].fields.treatment);
        $('#id_treatment').val(data[0].fields.treatment);
        $('#id_first_name').val(data[0].fields.first_name);
        $('#id_last_name').val(data[0].fields.last_name);
        $('#id_email').val(data[0].fields.email);
        $('#id_phone').val(data[0].fields.phone);
    });
  });

  // Edit contact
  $('#edit_contact_form').on('submit', function(e) {
    e.preventDefault();
    edit_contact_post();
  });

  {% for contact in contacts %}
    function edit_contact_post() {
      let contact_edit_id = $('#contact_edit_id').val();
      console.log(contact_edit_id);
      $.ajax({
        url: "{% url 'core:contact_edit' pk=contact.pk %}",
        type: "POST",
        data: {
          contact_edit_id: contact_edit_id,
          treatment: $('#id_treatment').val(),
          first_name: $('#id_first_name').val(),
          last_name: $('#id_last_name').val(),
          email: $('#id_email').val(),
          phone: $('#id_phone').val(),
        },
        success: function(response) {
          console.log(response.status);
          // remove os valores dos inputs
          $('#edit_contact_form')[0].reset();
          // Remove o novo contato da lista
          $('#dismiss_edit_contact_close').click();
          // Não fiz update dos items
          location.reload();
        },
        error: function(xhr, errmsg, err) {
          console.log('Ocorreu um erro!');
        },
      });
    }
  {% endfor %}

  // Insere valores nos campos de del_contact_form
  $('.js-delete-contact').on('click', function() {
    $('#contact_id').remove();
    $('#name_id').remove();
    let id = $(this).data('id');
    let contact = $(this).data('contact');
    $('#id_del_contact').append('<input id="contact_id" name="contact_id" style="display:none;" value="' + id + '">');
    $('#id_del_contact').append('<p id="name_id">' + contact + '</p>');
  });

  // Delete contact
  $('#del_contact_form').on('submit', function(e) {
    e.preventDefault();
    del_contact_post();
  });

  {% for contact in contacts %}
    function del_contact_post() {
      console.log("{% url 'core:contact_delete' pk=contact.pk %}");
      let contact_id = $('#contact_id').val();
      console.log(contact_id);
      $.ajax({
        url: "{% url 'core:contact_delete' pk=contact.pk %}",
        type: "POST",
        data: {
          contact_id: contact_id,
        },
        success: function(response) {
          console.log(response.status);
          // remove os valores dos inputs
          $('#del_contact_form')[0].reset();
          // Remove o novo contato da lista
          $('#dismiss_del_contact_close').click();
          $('#item_' + contact_id).fadeTo('slow', 0).slideUp(500, function(){
            $(this).remove();
          });
        },
        error: function(xhr, errmsg, err) {
          console.log('Ocorreu um erro!');
        },
      });
    }
  {% endfor %}

  </script>
{% endblock js %}

myproject/core/templates/nav.html
<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="navbar-header">
     
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
       <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
    </button> <a class="navbar-brand" href="#">Frontend Experience</a>
  </div>
  
  <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="https://github.com/rg3915/frontend-experience" target="_blank"><i class="fa fa-lg fa-github"></i></a>
        </li>
      </ul>
    </div>

</nav>